### ISSUE TITLE
Custom Drawing Engine

### ISSUE THREAD

**Issue by BenStigsen** [BenStigsen/vanim#2]
Having a custom drawing and buffer system, will allow one to modify the engine more easily and it will give more control when transforming between text, polygons and filled polygons.

---

To separate two different processes, "plotting" refers to creating the image in the buffer, "drawing" refers to showing it in the window.

There'll be different types of plotting. 
- `plot_empty_*()` will plot the outline of a shape
- `plot_filled_*()` will plot the shape filled
- `plot_pointy_*()` will only plot vertices

Below the different types of plotting can be seen (each circle represents a point):
![image](https://user-images.githubusercontent.com/24865450/125891178-23ac550f-a68e-4dc9-8908-f10fa5b73db6.png)

Here "Pointy" is the one that's most efficient to draw, since we have the entire shape described with just corner points. This also allows for optimizations. With `gg.Context.draw_empty_poly([]f32)` it will draw a line between each point, but we will only have to keep track of very few points. This makes easing calculations faster and it uses less memory, which also means it's less intensive to precalculate the entire animation.

I'm still considering whether the buffer being plotted, should have data as 4 bytes to describe RGBA color, or whether to just keep it one byte (true or false) if that pixel should be drawn. Doing the latter makes coloring different parts of the animation a bit harder, but it would require less memory, be more performant and it would be easier to create a system for it. (This does not mean that you're not able to color the animation, you will still be able to do `animation.draw(color gx.Color)` when you choose to draw your animation).

---

**Canvas**
- [x] `struct Canvas`
  - [x] `Canvas.buffer`
  - [x] `Canvas.image`

**Plotting**
- [x] `plot_pixel()`
- [x] `plot_line()`
- [x] `plot_empty_rect()`
- [x] `plot_filled_rect()`
- [x] `plot_pointy_rect()`
- [x] `plot_empty_triangle()`
- [x] `plot_filled_triangle()`
- [x] `plot_pointy_triangle()`
- [x] `plot_empty_circle()`
- [x] `plot_filled_circle()`
- [x] `plot_empty_polygon()`
- [x] `plot_pointy_polygon()`
- [x] `plot_filled_polygon()`

**Animation**
- [x] Rework to support canvas buffer

**Easing**
- [x] Raw buffer calculation
- [x] Empty poly easing
- [x] Filled poly easing
- [x] Pointy poly easing
- [x] Compatibility between plot types

**Optimization**
This is now being tracked here: https://github.com/BenStigsen/vanim/issues/3

**Comment by BenStigsen** [comment]
> I'm still considering whether the buffer being plotted, should have data as 4 bytes to describe RGBA color, or whether to just keep it one byte (true or false) if that pixel should be drawn. Doing the latter makes coloring different parts of the animation a bit harder, but it would require less memory, be more performant and it would be easier to create a system for it. (This does not mean that you're not able to color the animation, you will still be able to do animation.draw(color gx.Color) when you choose to draw your animation.

To avoid constant conversion between a `gg.Image` and the canvas buffer, I've decided to make the buffer be `width * height * 4` in size, allowing for 4 bytes to describe one pixel with RGBA values. This of course takes 4x as much memory, but this just makes the code much simpler internally, and no conversion is required to create an image from it. If someone could find a way to make `gg` accept a `black/white` byte array, then I'd definitely prefer that, since it requires 4x less memory and less processing power.

The current system currently uses an array of points to draw the pixels, I'd still like for this to be possible, so that it's not required to go through the entire buffer each time when no new pixels has been added to it. This should be quite simple by making a boolean variable, each time something has been drawn to the buffer, this variable is going to turn true, which makes Vanim collect all points from the buffer. Where the animation is only going to affect those points, and not the entire buffer.

I've had quite the trouble with drawing algorithms, mainly when it comes to filling polygons, I'd very much like the scan-line algorithm to be used here, but it has been quite a mess to make it work, but so far, all other shapes work.

So while a buffer and plotting system has been made, some changes needs to be made with `vanim.Animation` struct. 
Currently you do something like:
```v
mut anim := vanim.Animation{
  from: array_to_points[0, 50, 100, 100, 0, 100] // triangle
  to: array_to_points[0, 0, 100, 0, 100, 100, 0, 100] // square
  duration: 200
}

app.animations << anim
```
But with this overhaul, it's going to use a `Canvas` struct. Still deciding how to make this easy and simple, but I was thinking something like:
```v
mut anim := vanim.Animation{
  from: vanim.new_canvas(width: 200, height: 200)
  to: vanim.new_canvas(width: 200, height: 200)
  duration: 200
}

anim.from.plot_empty_triangle(0, 50, 100, 100, 0, 100)
anim.to.plot_empty_rectangle(0, 0, 100, 100)

app.animations << anim
```
I'm still trying to simplify the system, but the goal is that the user can just plot what they want, then Vanim takes care of the drawing (but the user still has the option to do some optimizations).


With this new system, the easing system also needs a bit of a rework. But that should be relatively trivial to implement.

**Comment by BenStigsen** [comment]
Okay, so I've made `plot_filled_triangle()` and `plot_filled_polygon()` work (for now).

For filling a triangle I went with: https://stackoverflow.com/questions/2049582/how-to-determine-if-a-point-is-in-a-2d-triangle/9755252#9755252
For filling a polygon I decided to go with: https://wrf.ecse.rpi.edu/Research/Short_Notes/pnpoly.html#The%20C%20Code 

Now my focus will be moved to functions that increase ease-of-use as well as change the easing and animation system.

**Comment by penguindark** [comment]
The filling algo IMHO is an overkilling code to draw a filled polygon.

**Comment by BenStigsen** [comment]
> The filling algo IMHO is an overkilling code to draw a filled polygon.

For now this will do, when I merge to master, I'll definitely be looking for alternatives, with the main focus being on performance.

I'm curious, what do you think is overkill about it and what do you have in mind?

**Comment by penguindark** [comment]
In my opinion it's overkill the need to check every pixel,
you can check only the vertical borders then make a custom `draw_horizontal_line` to fill the polygon.
You can have a look at my filler: https://github.com/vlang/v/blob/016240d00be5a6efc52ce3691a14ea3af3fd02ca/vlib/x/ttf/render_bmp.v#L88
It does exactly this job.
Obviously other algos are available in papers or on web :)

**Comment by BenStigsen** [comment]
Optimally Vanim would use Scanline rendering, I've just had quite the trouble trying to implement it.

**Comment by penguindark** [comment]
The .ttf filler is an implementation of the Scanline rendering, I suggest you to start from it :)

**Comment by BenStigsen** [comment]
Yeah it looked like it was, I just wasn't sure where you were checking for edges even though I looked through it multiple times, but after taking another look it's quite obvious. https://github.com/vlang/v/blob/016240d00be5a6efc52ce3691a14ea3af3fd02ca/vlib/x/ttf/render_bmp.v#L119-L130

**Comment by BenStigsen** [comment]
Yep, scanline it is, I'll implement it for triangles and polygons, then I'll continue with the animation system.

**Comment by BenStigsen** [comment]
WIP animation easing and drawing has now been added.

**Comment by BenStigsen** [comment]
## 75% Buffer Reduction
So, after a lot of brainstorming and some discussion in the Discord, I looked around in the `stbi` file, and found out that it supports PGM (Portable GrayMap) and (PPM) Portable PixMap. This format is very raw, with the header only being:
```
P5
100 100
255
```
`P5` is the file format. This is a greyscale map.
`100 100` is the width and height.
`255` is the max color value, this could also be `1` to have a buffer of black/white pixels.
After this header, it just raw pixels described byte after byte.
For color support the `P6` format can be used for RGB.

Using this new format allows for one to create an image directly from the buffer, while also allowing direct pixel manipulation in an image compatible buffer. Doing this means that the buffer can be loaded directly into an image and drawn, without first having to convert values.
Using this format, each pixel is described by 1 byte, meaning that it's a 75% reduction in buffer size. I do still intend on supporting RGB colors, with the use of the P6 format.

---

## Drawing
WIP drawing has been added, currently it supports buffer drawing, point drawing and image drawing. Now the next step is improving ease-of-use as well as easing between filled, empty and pointy canvasses with different data storage modes (buffer, points, images).

**Comment by BenStigsen** [comment]
Easing between buffer and point drawing is now possible. 
Due to a limitation with `gg` not allowing one to load / update images after initialization, the next step will be to implement our own image loading function or create an issue on the official vlang GitHub (which I'm already doing). If however the function had to be implemented manually, this means that Vanim would have its own image cache. Then loading images would be done with `stbi` and then there'd have to be direct function calls to Sokol.

**Comment by BenStigsen** [comment]
I might have a solution to this. `Canvas.image` could create a `gg.new_streaming_image()` when `animation.setup()` is called. Then we could update that streaming image. We just need to keep track of whether the image has been updated and not.

**Comment by BenStigsen** [comment]
> I might have a simpler solution to this. `Canvas.image` could create a `gg.new_streaming_image()` when `animation.setup()` is called. Then we could update that streaming image. We just need to keep track of whether the image has been updated and not.

Nevermind, now I remember the problem I had with this solution earlier. Even though it's possible to specify the number of channels the streaming image has, it does not change the pixel format. So even though I might have 1 channel (1 value to describe color), the pixel format still gets set as RGBA (4 bytes).
https://github.com/vlang/v/issues/10965

**Comment by BenStigsen** [comment]
Alright, after a lot of messing around, trying to debug and getting help in the vlang Discord, it seems that for some reason streaming images with 1 byte buffers has to a multiple of 4 in size... For some reason, I have no idea why. If I were to update the pixel data with an empty buffer, it would still draw pixels at the bottom. This is not Vanim related, this is has something to do with Sokol or `gg`.

**Comment by BenStigsen** [comment]
I've now opened an issue for one of the problems. I'll probably open a separate issue for the "multiple of 4" problem. https://github.com/vlang/v/issues/10989

**Comment by BenStigsen** [comment]
I added a workaround to the image bleeding issue. It should now be fixed, but it does automatically resize the canvas to a multiple of 4, which might not be a good solution.

So this:
```v
canvas := vanim.new_canvas(17, 25)
println(canvas.width)
println(canvas.height)
```
Will return:
```
20
28
```

**Comment by BenStigsen** [comment]
Everything is almost ready to be merged. There are some temporary solutions for now, but the custom drawing engine and buffer system is pretty much done.

**Comment by penguindark** [comment]
good! well done.

**Comment by BenStigsen** [comment]
The engine plotting, easing and drawing just got rewritten. It is all much simpler and memory efficient. Now it doesn't have `.raw` and `.image` any more.
This will also simplify the other issues with optimizations and more. The details for this change can be found here: https://github.com/BenStigsen/vanim/discussions/7

**Before**
```
==================================================================================
 Language               Files        Lines         Code     Comments       Blanks
==================================================================================
 Coq                        5          977          813            0          164
----------------------------------------------------------------------------------
 .\vanim.v                              22           17            0            5
 .\canvas.v                            150          121            0           29
 .\easing.v                            311          269            0           42
 .\animation.v                         147          119            0           28
 .\plot.v                              347          287            0           60
==================================================================================
 Total                      5          977          813            0          164
==================================================================================
```

**After**
```
==================================================================================
 Language               Files        Lines         Code     Comments       Blanks
==================================================================================
 Coq                        5          810          667            0          143
----------------------------------------------------------------------------------
 .\vanim.v                              19           16            0            3
 .\canvas.v                             46           35            0           11
 .\animation.v                         113           90            0           23
 .\plot.v                              374          300            0           74
 .\easing.v                            258          226            0           32
==================================================================================
 Total                      5          810          667            0          143
==================================================================================
```

Lines of code went from `813` to `667` with this change, an 18% decrease in project size.
